the-vampiire/hacktoberithms

- .gitignore
- Sum of All Numbers/solution.py
Solution for 'Sum of All Numbers'.
using max and min function to fill up range function requirement then sum all of the number on it.
> [*] solution for issue 1

- Profile Lookup/solution.py
Solution for Profile Lookup, enumerate the contacts value, then check if the firstname is exist, if not return 'no such contact for {input_name}', otherwise check the field, if field not exist return 'no such property of {input_field}'.
> [*] solution for Profile Lookup

- beginner/sum-of-all-numbers-rosdyana.py
- beginner/sum_of_all_numbers_mikelane.py
Complete the challenge in a pythonic way. Also adds doctests.
Closes: 1
> 1 Completes challenge and adds doctests

- beginner/profile-lookup-rosdyana.py
- beginner/profile_lookup_mikelane.py
> 2 Add pythonic solution and doctests

- wizard_apprentice/power-hungry_yoch.py
This problem not seems too difficult, the key point is to separate the negative, positive and zero numbers.
My approach is to check first if output can be positive, zero or must be negative, and treat the problem accordingly.
> solution for the Power Hungry problem

- intermediate/mutations_yoch.py
Simple solution using python sets, including tests.
> solution to mutations problem

- beginner/sum-of-all-numbers_ChingLingYeung.py
approach:
- make sure input is correct (list with 2 elements)
- double element value if both element is the same
- for elements with different values, incrementally add to sum
- return the final sum
no main method written, import and use function from terminal
> my solution to issue #1

- beginner/sum-of-all-numbers_loukotal.py
Nice introductory challenge. I think I managed to solve it in a pythonic way, choosing min and max from the list, which handles the input being mismatched. 
Also a very nice to learn about pull requests and test it out!
> Add solution to challenge/issue 1

- beginner/profile-lookup_loukotal.py
I made use of the dict method .get, where you can specify a value if the key is not present in the dict.
> Add solution for issue 2

- intermediate/mutations_loukotal.py
First I sorted the strings by length and named them short and long. Then I iterate over the short one to see if a letter is in the long one. If it is not, I return False. If the loop finishes I return True, which means that every letter in the short string is in the long string.
> Add solution for issue 3

- beginner/profile-lookup_loukotal.py
- beginner/sum-earnings_loukotal.py
- beginner/sum-of-all-numbers_loukotal.py
- intermediate/mutations_loukotal.py
Not really a smart solution. Checking for validity of the input in a for loop and then handling the streak.
> Issue 8 solution

- tough_stuff/braille-translation_joshhacksthings.py
Brute force approach.
Break down string into characters, for each character, perform two actions:
1. Find the (lower case) character in dict of binary braille code
2. If upper case, add upper case modifier
Finally, append binary to string.
Unit test ideas taken from challenge problem
> 14 solution

- beginner/sum-of-all-numbers_vinicius121.py
My approach consisted in sum all the values in range between the max and the min value in the array.
> Add sum-of-all-numbers_vinicius121

- intermediate/mutation_codilis.py
I made 2 counters that counts the number of times an alphabet appear in a string and if that appearance is greater in the second string then the function will return false.
> Solution for mutation problem

- beginner/sum-of-all-numbers_yoch.py
use arithmetic sequence formula
> solution for Sum All of Numbers problem

- beginner/sum-earnings_yoch.py
> solution for Sum Earnings problem

- beginner/profile-lookup_vinicius121.py
Added profile-lookup solution. It verifies if the name and the field exists and if so displays the requested field.
> Add profile-lookup_vinicius121

- beginner/profile-lookup_vinicius121.py
- beginner/sum-earnings_vinicius121.py
Add solution for sum-earnings. It first verifies if the string contains any character. If so returns 0.
Then splits by ',' and verifies if any token is empty. If so returns 0
Then verifies if all the numbers are less or equal then 0. If so returns 0
Finally, it performs the sum by also verifying the final condition of streak.
> 8 solution

- tough_stuff/braille-translation_Kushagra-0801.py
Iterates through the input, appending the braille equivalent to a list, which is then joined and returned.
Includes a test table and function.
> Solution to Issue #14.

- intermediate/mutations_nainys.py
Solution for mutation problem by converting strings to list and checking that every element of second list is present in first list(ensuring letter count).
> Mutations(Issue 3) solution

- wizard_apprentice/lovely-lucky-lambs_Kushagra-0801.py
For the most generous case -
1. Number of lambs given, goes as powers of 2.
2. Finding the bit length of the total lambs and subtracting 1 gives the number of henchmen.
For the most stingy case -
1. Number of lambs given, goes as fibonacci series.
2. Use functools.lru_cache for memoization to find fibonacci number.
3. Find number of iterations till the sum is not greater than total lambs.
> Solution to Issue #15

- beginner/sum-of-all-numbers_david.py
> Beginner Problem #1 Solution

- intermediate/multiple_cash_registers_thetrain2000.py
This one was actually quite the challenge to brainstorm, fun problem.
For issue #68.
> Solve multiple cash registers

- beginner/sum-earnings_Kushagra-0801.py
1. Make a list of the numbers using list and map.
* Raises ValueError if other characters are present.
* Doesn't work for spaces after/before commas.
2. Also count the number of commas in the input and add 1.
* If length of list not equal to this, then raise ValueError.
3. If ValueError is raised, print default output ('0').
4. Iterate through the list, adding to an initial balance of 0.
* If balance becomes negative, reassign 0 as balance.
5. Print final balance value.
> Solution to issue 8

- beginner/sum-earnings-mikelane.py
I changed my filename so that it matches with everyone else. Also I simplified the sum-earnings a bit.
> 8 Update filename

- beginner/sum-of-all-numbers-gettaplay.py
This is based on the mathematical property of sum of elements in arithmetic progression . This  works in O(1) comparing to the O(n) time complexity provided.
> Sum of all numbers working in constant time

- intermediate/Multiple_Cash_Registers_kajchang.py
> Solve Cash Register Problem

- beginner/sum-of-all-numbers_deepak.py
Resolves Issue #1 
Added Sum of all numbers
python2.7 must be installed
In Linux from terminal:
Navigate to the folder and execute:
python sum_of_all_numbers_deepak.py
> Solution to #1

- beginner/sum-earnings_dsargento.py
- beginner/sum-of-all-numbers_dsargento.py
Use python cli to execute the file (provided with 1 test case, the one in the subject, the program will sort any other list if it's reversed)
> 1 solution

- beginner/sum-earnings_dsargento.py
The function checks that the cast to int is correct using a try/except block, after splitting the string.
Simply use the function with the test string in the .py file, and execute using the cli (i used python 3.6)
> #8 solution

- tough_stuff/Braille_Translation_aashbaugh16.py
New to python so it is not very streamlined but will continue to research and work on it.
> My solution

- beginner/profile-lookup_dsargento.py
usage ``python profile-lookup_dsargento.py``
provided with some test cases
> 2-solution

- intermediate/mutation_dsargento.py
checks for elements in first string using for loop
usage: ``python mutation_dsargento.py``
> 3 solution

- beginner/sum-of-all-numbers_Zelbot.py
Incrementally increasing / counting can be easily achieved using loops, where I chose to implement a for-loop.
In order to use the sum_all function, simply print its return value.
> sum_all using a for loop

- beginner/profile-lookup_Zelbot.py
- beginner/sum-of-all-numbers_Zelbot.py
Iterates through all dictionaries in the contacts list.
If the name and the corresponding field is found in the current dictionary, the value of the field is returned.
If the name is found in the current dictionary but the field is not present, "No such property" is returned.
If the loop has iterated through all dictionaries and has not found the name in any of the dictionaries values, "No such contact" is returned.
Use the look_up_profile function by printing its return value.
> profile-lookup tested solution

- beginner/profile-lookup_Zelbot.py
- beginner/sum-earnings_Zelbot.py
- beginner/sum-of-all-numbers_Zelbot.py
If any of the mentioned errors occur (the string isn't seperated correctly, values aren't numbers, no money has been earned) the sum_earnings function returns 0.
If the current value in the loop is smaller than the current sum, the sum is reset to 0.
The final sum is then returned.
Use the sum_earnings function by printing its return value.
> sum_earnings tested solution with a focus on readable error handling

- beginner/profile-lookup_Zelbot.py
- beginner/sum-earnings_Zelbot.py
- beginner/sum-of-all-numbers_Zelbot.py
- intermediate/mutations_Zelbot.py
Get a list of letters by creating a set of a list of the second string.
Check if all of the letters are present in the first string using the all() function.
If all letters are present, return True, otherwise return False.
Use the mutations function by printing its return value (assuming we pass a list of two strings).
> mutations solution using set() and all()

- beginner/sum_of_all_numbers_ezekohon.py
> solution to sum of all numbers

- beginner/SumEarnings_Araetoro
I am new to coding so I did get stuck in several areas along the way. I have been working on this for a few days and have learned some new built-in python functions which were really useful! I had a lot of trouble trying to push my work upstream, and ultimately went to my repo on GitHub to add my file, I'm not sure if this works quite right either, Hacktoberfest is definitely a big learning experience for me!
> 8-Solution

- README.md
updated readme
added javascript / challenge directories
> Update for js

- python/beginner/sum-earnings_fredbaa.py
> added solution for sum_earnings problem

- python/intermediate/mutations_fredbaa.py
> added solution for mutations problem

- python/beginner/sum-of-all-numbers_XDBGAMES.py
> sum-of-all-numbers_XDBGAMES.py

- javascript/intermediate/multiple-cash-registers_sylvain1811.js
I've made `minIndex` local scoped and added a test method using assert from node according to recommandation from @the-vampiire in PR #128.
> Update 68-solution-javascript tests according to recommendation

- python/beginner/Sum_Earnings_AnilKumarTeegala.py
Solved Sum Earnings #8 issue for the beginners
> Solved Sum Earnings #8

- python/beginner/sum-earnings_ljsauer.py
I approached this problem with several if/else statements initially and was able to get it functioning, except for being able to re-start the count for earnings.
I got the idea to simplify my code into the try/except format from Stack Overflow after looking into how to handle multiple exceptions with the same output. I also came across the use of the max() method to restart the earnings count if spending > earning, instead of using another loop inside my for loop.
To run, just call the function and feed in your input as outlined in the challenge.
Thanks!
> Solution for sum-earnings

- python/beginner/Profile-Lookup_Sokom141.py
Issue: #2 
1. Start the script
2. Enter the contact's name and the field when prompted
> Profile Lookup solution

- javascript/beginner/sum-of-all-numbers_hp250497.js
Added javascript logic for sum of all numbers #1
> Added logic for Sum of All Numbers
